"""baseline — initial schema placeholder for MIHAJA_ERP_PRO

Revision ID: 001_baseline
Revises:
Create Date: 2026-09-07

IMPORTANT:
This is a structural placeholder. Replace it by running against an empty
PostgreSQL database:

    export FLASK_APP=app:create_app
    flask db migrate -m "baseline"

Then carefully review the generated file before committing.
"""
from alembic import op
import sqlalchemy as sa

revision = '001_baseline'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # Placeholder — replace with real autogenerated operations
    pass

def downgrade():
    pass
