"""add entrepots, stock_entrepot, and stock_min/max

Revision ID: 07efbe5e9c15
Revises: m1n2o3p4q5r6
Create Date: 2026-09-11 11:29:43.332681
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07efbe5e9c15'
down_revision: Union[str, None] = 'm1n2o3p4q5r6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrepots',
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('responsable', sa.String(length=100), nullable=True),
    sa.Column('capacite', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('principal', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['utilisateurs.id'], name='fk_basemodel_created_by', use_alter=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_basetenantmodel_tenant_id', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['utilisateurs.id'], name='fk_basemodel_updated_by', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entrepots', schema=None) as batch_op:
        batch_op.create_index('idx_entrepot_nom', ['nom'], unique=False)
        batch_op.create_index(batch_op.f('ix_entrepots_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_entrepots_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('stocks_entrepot',
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('entrepot_id', sa.Integer(), nullable=False),
    sa.Column('quantite', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('seuil_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('seuil_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['utilisateurs.id'], name='fk_basemodel_created_by', use_alter=True),
    sa.ForeignKeyConstraint(['entrepot_id'], ['entrepots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produit_id'], ['produits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='fk_basetenantmodel_tenant_id', use_alter=True),
    sa.ForeignKeyConstraint(['updated_by'], ['utilisateurs.id'], name='fk_basemodel_updated_by', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stocks_entrepot', schema=None) as batch_op:
        batch_op.create_index('idx_stock_entrepot_entrepot', ['entrepot_id'], unique=False)
        batch_op.create_index('idx_stock_entrepot_produit', ['produit_id', 'entrepot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocks_entrepot_entrepot_id'), ['entrepot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocks_entrepot_produit_id'), ['produit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocks_entrepot_tenant_id'), ['tenant_id'], unique=False)

    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_min', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('stock_max', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produits', schema=None) as batch_op:
        batch_op.drop_column('stock_max')
        batch_op.drop_column('stock_min')

    with op.batch_alter_table('stocks_entrepot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_entrepot_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_stocks_entrepot_produit_id'))
        batch_op.drop_index(batch_op.f('ix_stocks_entrepot_entrepot_id'))
        batch_op.drop_index('idx_stock_entrepot_produit')
        batch_op.drop_index('idx_stock_entrepot_entrepot')

    op.drop_table('stocks_entrepot')
    with op.batch_alter_table('entrepots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entrepots_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_entrepots_code'))
        batch_op.drop_index('idx_entrepot_nom')

    op.drop_table('entrepots')
    # ### end Alembic commands ###
