import os

AI_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'web', 'frontend', 'src', 'pages', 'AI.jsx')

with open(AI_FILE, 'w', encoding='utf-8') as f:
    f.write('import React, { useState, useEffect, useRef, useCallback } from \'react\';\r\n')
    f.write('import { aiService } from \'../services/api\';\r\n')
    f.write('import { useLocation } from \'react-router-dom\';\r\n')
    f.write('import { toast } from \'react-toastify\';\r\n')
    f.write('import { Card, CardContent, CardHeader, Typography, Box, Button, Paper, Chip, Avatar, Tooltip, Skeleton } from \'@mui/material\';\r\n')
    f.write('import MessageBubble from \'../components/MessageBubble\';\r\n')
    f.write('import ChatInput from \'../components/ChatInput\';\r\n')
    f.write('import { \r\n')
    f.write('  ChatBubbleOutline,\r\n')
    f.write('  TrendingUp,\r\n')
    f.write('  TrendingDown,\r\n')
    f.write('  AlertTriangle,\r\n')
    f.write('  Info,\r\n')
    f.write('  Lightbulb,\r\n')
    f.write('  Inventory,\r\n')
    f.write('  CreditCard,\r\n')
    f.write('  People,\r\n')
    f.write('  ShoppingCart,\r\n')
    f.write('  Forecast,\r\n')
    f.write('  Send,\r\n')
    f.write('  Inbox,\r\n')
    f.write('  Refresh,\r\n')
    f.write('  CheckCircle,\r\n')
    f.write('} from \'lucide-react\';\r\n\r\n')
    f.write('const icons = {\r\n')
    f.write('  stockRuptures: Inventory,\r\n')
    f.write('  anomalies: AlertTriangle,\r\n')
    f.write('  recommendations: Lightbulb,\r\n')
    f.write('  previsions: Forecast,\r\n')
    f.write('  trends: TrendingUp,\r\n')
    f.write('  insights: Info,\r\n')
    f.write('  clients: People,\r\n')
    f.write('  purchases: ShoppingCart,\r\n')
    f.write('  finances: CreditCard,\r\n')
    f.write('  demandPrediction: Forecast,\r\n')
    f.write('  lowStock: Inventory,\r\n')
    f.write('  customerDebts: CreditCard,\r\n')
    f.write('  topProducts: TrendingUp,\r\n')
    f.write('  supplierPriceChanges: ShoppingCart,\r\n')
    f.write('  pendingInvoices: CreditCard,\r\n')
    f.write('  quickStockHealth: Inventory,\r\n')
    f.write('  quickLowStock: Inventory,\r\n')
    f.write('  quickCustomerDebts: CreditCard,\r\n')
    f.write('  quickTopProducts: TrendingUp,\r\n')
    f.write('  quickSupplierPriceChanges: ShoppingCart,\r\n')
    f.write('  quickPendingInvoices: CreditCard,\r\n')
    f.write('};\r\n\r\n')
print('Header written')
