const { chromium } = require('playwright');
(async () => {
  console.log('SC1 — Inscription /register/company (persistance)');
  const browser = await chromium.launch({ headless: true, slowMo: 500 });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('http://localhost:3000/register/company', { waitUntil: 'load', timeout: 30000 });
  await page.waitForTimeout(1500);
  await page.screenshot({ path: 'sc1_load_check.png', fullPage: true });
  console.log('SC1 — Page chargée');
  await page.fill('#register-company-name', 'Mada Test ERP');
  await page.fill('#register-company-adresse', '12 Rue du Test');
  await page.fill('#register-company-ville', 'Antananarivo');
  await page.fill('#register-company-cp', '101');
  await page.fill('#register-company-prenom', 'Jean');
  await page.fill('#register-company-nom', 'Test');
  await page.fill('#register-company-email', 'jean.test@madatest.mg');
  await page.waitForTimeout(5000);
  await page.waitForTimeout(3000);
  const val = await page.$eval('#register-company-plan', sel => {
    const opts = Array.from(sel.options).filter(o => o.value && o.value !== '');
    return opts.length ? opts[0].value : 'gratuit';
  });
  await page.selectOption('#register-company-plan', val);
  await page.fill('#register-company-password', 'TestPass123!');
  await page.fill('#register-company-confirm', 'TestPass123!');
  await page.check('#register-company-terms');
  await page.click('button.auth-login__submit');
  await page.waitForTimeout(3000);
  const urlSC1 = page.url();
  console.log('SC1 URL finale:', urlSC1);
  await page.screenshot({ path: 'sc1_session_persistante.png', fullPage: true });
  await context.storageState({ path: 'storage_state.json' });
  console.log('SC1 — Session sauvegardée');
  await browser.close();
})();
