"""
Donnees de demonstration et valeurs par defaut adaptees au contexte
commercial malagache (grossiste, distributeur, semi-grossiste, boutique).

La monnaie utilisee est l'ariary (MGA / Ar). Les prix sont en MGA et
restent coherents avec une activite de gros / distribution.
"""

# ---------------------------------------------------------------------------
# Villes malgachomanes et codes postaux Madagascar
# ---------------------------------------------------------------------------
VILLES_MADAGAS = [
    {"ville": "Antananarivo", "code_postal": "101", "region": "Analamanga"},
    {"ville": "Antsirabe", "code_postal": "110", "region": "Vakinankaratra"},
    {"ville": "Fianarantsoa", "code_postal": "301", "region": "Haute Matsiatra"},
    {"ville": "Antsiranana", "code_postal": "201", "region": "Diana"},
    {"ville": "Mahajanga", "code_postal": "401", "region": "Boeny"},
    {"ville": "Toamasina", "code_postal": "501", "region": "Atsinanana"},
    {"ville": "Toliara", "code_postal": "601", "region": "Atsimo-Andrefana"},
    {"ville": "Morondava", "code_postal": "619", "region": "Menabe"},
    {"ville": "Antalaha", "code_postal": "206", "region": "Sava"},
    {"ville": "Ambovombe", "code_postal": "603", "region": "Androy"},
    {"ville": "Farafangana", "code_postal": "308", "region": "Atsimo-Atsinanana"},
    {"ville": "Manakara", "code_postal": "317", "region": "Vatovavy"},
    {"ville": "Sambava", "code_postal": "208", "region": "Sava"},
    {"ville": "Marovoay", "code_postal": "415", "region": "Boeny"},
    {"ville": "Maintirano", "code_postal": "418", "region": "Melaky"},
    {"ville": "Besalampy", "code_postal": "421", "region": "Melaky"},
    {"ville": "Moramanga", "code_postal": "514", "region": "Atsinanana"},
    {"ville": "Vatomandry", "code_postal": "516", "region": "Atsinanana"},
    {"ville": "Mahanoro", "code_postal": "510", "region": "Atsinanana"},
    {"ville": "Mananjary", "code_postal": "316", "region": "Vatovavy"},
    {"ville": "Nosy Be", "code_postal": "207", "region": "Diana"},
    {"ville": "Andapa", "code_postal": "205", "region": "Sava"},
    {"ville": "Bealanana", "code_postal": "433", "region": "Sofia"},
    {"ville": "Port-Bergé", "code_postal": "438", "region": "Sofia"},
    {"ville": "Mampikony", "code_postal": "434", "region": "Sofia"},
    {"ville": "Analalava", "code_postal": "422", "region": "Sofia"},
    {"ville": "Soanierana-Ivongo", "code_postal": "523", "region": "Analanjirofo"},
    {"ville": "Fenoarivo Atsinanana", "code_postal": "508", "region": "Analanjirofo"},
    {"ville": "Mananara Avaratra", "code_postal": "514", "region": "Analanjirofo"},
    {"ville": "Vavatenina", "code_postal": "518", "region": "Analanjirofo"},
    {"ville": "Marolambo", "code_postal": "513", "region": "Atsinanana"},
    {"ville": "Ihosy", "code_postal": "311", "region": "Ihorombe"},
    {"ville": "Ilakaka", "code_postal": "313", "region": "Ihorombe"},
    {"ville": "Betroka", "code_postal": "314", "region": "Anosy"},
    {"ville": "Ambositra", "code_postal": "306", "region": "Amoron'i Mania"},
    {"ville": "Fandriana", "code_postal": "304", "region": "Amoron'i Mania"},
    {"ville": "Manandriana", "code_postal": "305", "region": "Amoron'i Mania"},
    {"ville": "Ambohidratrimo", "code_postal": "105", "region": "Analamanga"},
    {"ville": "Andramasina", "code_postal": "106", "region": "Analamanga"},
    {"ville": "Anjozorobe", "code_postal": "107", "region": "Analamanga"},
    {"ville": "Manjakandriana", "code_postal": "116", "region": "Analamanga"},
    {"ville": "Soavinandriana", "code_postal": "118", "region": "Itasy"},
    {"ville": "Miarinarivo", "code_postal": "121", "region": "Itasy"},
    {"ville": "Arivonimamo", "code_postal": "112", "region": "Itasy"},
    {"ville": "Tsiroanomandidy", "code_postal": "119", "region": "Bongolava"},
    {"ville": "Tsiroanomandidy", "code_postal": "119", "region": "Bongolava"},
    {"ville": "Maintirano", "code_postal": "418", "region": "Melaky"},
    {"ville": "Morondava", "code_postal": "619", "region": "Menabe"},
    {"ville": "Miandrivazo", "code_postal": "616", "region": "Menabe"},
    {"ville": "Antsalova", "code_postal": "424", "region": "Melaky"},
    {"ville": "Belo sur Tsiribihina", "code_postal": "614", "region": "Menabe"},
    {"ville": "Ampanihy", "code_postal": "605", "region": "Atsimo-Andrefana"},
    {"ville": "Betioky", "code_postal": "607", "region": "Atsimo-Andrefana"},
    {"ville": "Tuléar", "code_postal": "601", "region": "Atsimo-Andrefana"},
    {"ville": "Sakaraha", "code_postal": "620", "region": "Atsimo-Andrefana"},
    {"ville": "Atsimo-Andrefana", "code_postal": "601", "region": "Atsimo-Andrefana"},
    {"ville": "Ejeda", "code_postal": "608", "region": "Atsimo-Andrefana"},
    {"ville": "Ambovombe", "code_postal": "603", "region": "Androy"},
    {"ville": "Beloha", "code_postal": "605", "region": "Androy"},
    {"ville": "Tsihombe", "code_postal": "609", "region": "Androy"},
    {"ville": "Fort-Dauphin", "code_postal": "614", "region": "Anosy"},
    {"ville": "Vangaindrano", "code_postal": "320", "region": "Atsimo-Atsinanana"},
    {"ville": "Farafangana", "code_postal": "308", "region": "Atsimo-Atsinanana"},
    {"ville": "Vondrozo", "code_postal": "323", "region": "Atsimo-Atsinanana"},
    {"ville": "Manakara", "code_postal": "317", "region": "Vatovavy"},
    {"ville": "Ikongo", "code_postal": "318", "region": "Vatovavy"},
    {"ville": "Mananjary", "code_postal": "316", "region": "Vatovavy"},
    {"ville": "Nosy Varika", "code_postal": "319", "region": "Vatovavy"},
    {"ville": "Sahambavy", "code_postal": "306", "region": "Haute Matsiatra"},
    {"ville": "Ambalavao", "code_postal": "303", "region": "Haute Matsiatra"},
    {"ville": "Côte Est", "code_postal": "301", "region": "Haute Matsiatra"},
]


def tel_madag(reste):
    """Construit un numero +261 fictif stable a partir d'un suffixe."""
    return f"+261 3{reste}"


# ---------------------------------------------------------------------------
# Catalogue produits (grossiste / distribution) en Ariary
# ---------------------------------------------------------------------------
# Prix ordonnes : grossiste < demi_gros < revendeur < vente (detail).
PRODUCTS_CATALOG = [
    {
        "nom": "Riz blanc Makalioka (sac 50 kg)",
        "categorie": "Riz & Cereales",
        "unite": "sac",
        "marque": "Lac Alaotra",
        "prix_achat_ht": 420000,
        "prix_vente_ht": 525000,
        "prix_grossiste": 505000,
        "prix_demi_gros": 515000,
        "prix_revendeur": 518000,
        "quantite_stock": 120,
        "seuil_alerte": 20,
        "seuil_critique": 8,
        "description_courte": "Riz local conditionne en sac de 50 kg",
    },
    {
        "nom": "Riz brise (sac 25 kg)",
        "categorie": "Riz & Cereales",
        "unite": "sac",
        "marque": "RSI Mada",
        "prix_achat_ht": 175000,
        "prix_vente_ht": 230000,
        "prix_grossiste": 215000,
        "prix_demi_gros": 222000,
        "prix_revendeur": 226000,
        "quantite_stock": 220,
        "seuil_alerte": 30,
        "seuil_critique": 15,
        "description_courte": "Riz brise / brisures pour la restauration collective",
    },
    {
        "nom": "Huile vegetale Loulou (1 L)",
        "categorie": "Huiles & Grains",
        "unite": "bouteille",
        "marque": "Loulou",
        "prix_achat_ht": 7000,
        "prix_vente_ht": 9500,
        "prix_grossiste": 8800,
        "prix_demi_gros": 9100,
        "prix_revendeur": 9300,
        "quantite_stock": 1800,
        "seuil_alerte": 250,
        "seuil_critique": 100,
        "description_courte": "Huile alimentaire 1 L, tres demandee en detail",
    },
    {
        "nom": "Huile de table 5 L (bidon)",
        "categorie": "Huiles & Grains",
        "unite": "bidon",
        "marque": "Hasi",
        "prix_achat_ht": 88000,
        "prix_vente_ht": 112000,
        "prix_grossiste": 103000,
        "prix_demi_gros": 108000,
        "prix_revendeur": 110000,
        "quantite_stock": 320,
        "seuil_alerte": 50,
        "seuil_critique": 25,
        "description_courte": "Bidon 5 L pour boucheries et detail",
    },
    {
        "nom": "Sucre blanc en poudre (1 kg)",
        "categorie": "Couleurs & Sucreries",
        "unite": "sachet",
        "marque": "Compania",
        "prix_achat_ht": 3600,
        "prix_vente_ht": 4800,
        "prix_grossiste": 4400,
        "prix_demi_gros": 4600,
        "prix_revendeur": 4700,
        "quantite_stock": 9000,
        "seuil_alerte": 1200,
        "seuil_critique": 500,
        "description_courte": "Sucre de canne blanc en sachet de 1 kg",
    },
    {
        "nom": "Farine de ble (sac 50 kg)",
        "categorie": "Farines & Pates",
        "unite": "sac",
        "marque": "Aux Mille",
        "prix_achat_ht": 140000,
        "prix_vente_ht": 185000,
        "prix_grossiste": 174000,
        "prix_demi_gros": 180000,
        "prix_revendeur": 182000,
        "quantite_stock": 140,
        "seuil_alerte": 25,
        "seuil_critique": 12,
        "description_courte": "Farine de ble pour boulangeries et pates",
    },
    {
        "nom": "Eau minerale 2 L (pack 6)",
        "categorie": "Eaux & Boissons",
        "unite": "pack",
        "marque": "Source Tiaca",
        "prix_achat_ht": 7800,
        "prix_vente_ht": 10500,
        "prix_grossiste": 9800,
        "prix_demi_gros": 10100,
        "prix_revendeur": 10300,
        "quantite_stock": 750,
        "seuil_alerte": 120,
        "seuil_critique": 60,
        "description_courte": "Pack de 6 bouteilles d'eau minerale 1,5 L",
    },
    {
        "nom": "Boisson gazeuse locale (1,5 L)",
        "categorie": "Eaux & Boissons",
        "unite": "bouteille",
        "marque": "VCore",
        "prix_achat_ht": 4500,
        "prix_vente_ht": 6800,
        "prix_grossiste": 6100,
        "prix_demi_gros": 6400,
        "prix_revendeur": 6600,
        "quantite_stock": 900,
        "seuil_alerte": 150,
        "seuil_critique": 70,
        "description_courte": "Soda orange local 1,5 L, tres consomme",
    },
    {
        "nom": "Biscuit Vitel (250 g)",
        "categorie": "Biscuits & Gouters",
        "unite": "paquet",
        "marque": "Vitelo",
        "prix_achat_ht": 1400,
        "prix_vente_ht": 2100,
        "prix_grossiste": 1900,
        "prix_demi_gros": 2000,
        "prix_revendeur": 2050,
        "quantite_stock": 6000,
        "seuil_alerte": 900,
        "seuil_critique": 400,
        "description_courte": "Biscuits sucre 250 g, grande rotation",
    },
]