
PERMISSION_DEFINITIONS = {
    "product.view": {"module": "product", "action": "view", "description": "Voir les produits"},
    "product.create": {"module": "product", "action": "create", "description": "Creer des produits"},
    "product.update": {"module": "product", "action": "update", "description": "Modifier des produits"},
    "product.delete": {"module": "product", "action": "delete", "description": "Supprimer des produits"},
    "stock.view": {"module": "stock", "action": "view", "description": "Voir les stocks"},
    "stock.update": {"module": "stock", "action": "update", "description": "Modifier les stocks"},
    "sale.view": {"module": "sale", "action": "view", "description": "Voir les ventes"},
    "sale.create": {"module": "sale", "action": "create", "description": "Creer des ventes"},
    "sale.update": {"module": "sale", "action": "update", "description": "Modifier des ventes"},
    "user.view": {"module": "user", "action": "view", "description": "Voir les utilisateurs"},
    "user.create": {"module": "user", "action": "create", "description": "Creer des utilisateurs"},
    "user.update": {"module": "user", "action": "update", "description": "Modifier des utilisateurs"},
    "report.view": {"module": "report", "action": "view", "description": "Voir les rapports"},
    "client.view": {"module": "client", "action": "view", "description": "Voir les clients"},
    "client.create": {"module": "client", "action": "create", "description": "Creer des clients"},
    "client.update": {"module": "client", "action": "update", "description": "Modifier des clients"},
    "invoice.view": {"module": "invoice", "action": "view", "description": "Voir les factures"},
    "invoice.create": {"module": "invoice", "action": "create", "description": "Creer des factures"},
    "invoice.update": {"module": "invoice", "action": "update", "description": "Modifier des factures"},
    "payment.view": {"module": "payment", "action": "view", "description": "Voir les paiements"},
    "payment.create": {"module": "payment", "action": "create", "description": "Creer des paiements"},
    "quote.view": {"module": "quote", "action": "view", "description": "Voir les devis"},
    "quote.create": {"module": "quote", "action": "create", "description": "Creer des devis"},
    "supplier.view": {"module": "supplier", "action": "view", "description": "Voir les fournisseurs"},
    "supplier.create": {"module": "supplier", "action": "create", "description": "Creer des fournisseurs"},
    "supplier.update": {"module": "supplier", "action": "update", "description": "Modifier des fournisseurs"},
    "purchase_order.view": {"module": "purchase_order", "action": "view", "description": "Voir les commandes d'achat"},
    "purchase_order.create": {"module": "purchase_order", "action": "create", "description": "Creer des commandes d'achat"},
    "profile.view": {"module": "profile", "action": "view", "description": "Voir son profil"},
    "profile.update": {"module": "profile", "action": "update", "description": "Modifier son profil"},
    "compte.view": {"module": "compte", "action": "view", "description": "Voir les comptes"},
    "compte.create": {"module": "compte", "action": "create", "description": "Creer des comptes"},
    "compte.update": {"module": "compte", "action": "update", "description": "Modifier des comptes"},
    "compte.delete": {"module": "compte", "action": "delete", "description": "Supprimer des comptes"},
    "ecriture.view": {"module": "ecriture", "action": "view", "description": "Voir les ecritures"},
    "ecriture.create": {"module": "ecriture", "action": "create", "description": "Creer des ecritures"},
    "ecriture.update": {"module": "ecriture", "action": "update", "description": "Modifier des ecritures"},
    "ecriture.delete": {"module": "ecriture", "action": "delete", "description": "Supprimer des ecritures"},
    "tresorerie.view": {"module": "tresorerie", "action": "view", "description": "Voir la tresorerie"},
    "tresorerie.create": {"module": "tresorerie", "action": "create", "description": "Creer des mouvements de tresorerie"},
    "tresorerie.update": {"module": "tresorerie", "action": "update", "description": "Modifier des mouvements de tresorerie"},
    "tresorerie.delete": {"module": "tresorerie", "action": "delete", "description": "Supprimer des mouvements de tresorerie"},
}

ROLE_PERMISSIONS = {
    "super_admin": ["*"],
    "admin": ["*"],
    "manager": [
        "product.create", "product.update", "product.delete", "product.view",
        "stock.view", "stock.update",
        "sale.view", "sale.create", "sale.update",
        "user.view", "user.create", "user.update",
        "report.view",
        "client.view", "client.create", "client.update",
        "invoice.view", "invoice.create", "invoice.update",
        "payment.view", "payment.create",
    ],
    "sales": [
        "product.view",
        "sale.view", "sale.create",
        "client.view", "client.create", "client.update",
        "quote.view", "quote.create",
        "invoice.view",
    ],
    "stock": [
        "product.view", "product.create", "product.update",
        "stock.view", "stock.update",
        "supplier.view", "supplier.create", "supplier.update",
        "purchase_order.view", "purchase_order.create",
        "sale.view",
    ],
    "accountant": [
        "product.view",
        "invoice.view", "invoice.create", "invoice.update",
        "payment.view", "payment.create",
        "report.view",
        "sale.view",
        "client.view",
        "compte.view", "compte.create", "compte.update", "compte.delete",
        "ecriture.view", "ecriture.create", "ecriture.update", "ecriture.delete",
        "tresorerie.view", "tresorerie.create", "tresorerie.update", "tresorerie.delete",
    ],
    "user": [
        "product.view",
        "profile.view", "profile.update",
    ],
}

PERMISSIONS = ROLE_PERMISSIONS
