
PERMISSION_DEFINITIONS = {
    "product.view": {"module": "product", "action": "view", "description": "Voir les produits"},
    "product.create": {"module": "product", "action": "create", "description": "Creer des produits"},
    "product.update": {"module": "product", "action": "update", "description": "Modifier des produits"},
    "product.delete": {"module": "product", "action": "delete", "description": "Supprimer des produits"},
    "stock.view": {"module": "stock", "action": "view", "description": "Voir les stocks"},
    "stock.update": {"module": "stock", "action": "update", "description": "Modifier les stocks"},
    "sale.view": {"module": "sale", "action": "view", "description": "Voir les ventes"},
    "sale.create": {"module": "sale", "action": "create", "description": "Creer des ventes"},
    "sale.update": {"module": "sale", "action": "update", "description": "Modifier des ventes"},
    "sale.delete": {"module": "sale", "action": "delete", "description": "Supprimer des ventes"},
    "user.view": {"module": "user", "action": "view", "description": "Voir les utilisateurs"},
    "user.create": {"module": "user", "action": "create", "description": "Creer des utilisateurs"},
    "user.update": {"module": "user", "action": "update", "description": "Modifier des utilisateurs"},
    "report.view": {"module": "report", "action": "view", "description": "Voir les rapports"},
    "client.view": {"module": "client", "action": "view", "description": "Voir les clients"},
    "client.create": {"module": "client", "action": "create", "description": "Creer des clients"},
    "client.update": {"module": "client", "action": "update", "description": "Modifier des clients"},
    "client.delete": {"module": "client", "action": "delete", "description": "Supprimer des clients"},
    "invoice.view": {"module": "invoice", "action": "view", "description": "Voir les factures"},
    "invoice.create": {"module": "invoice", "action": "create", "description": "Creer des factures"},
    "invoice.update": {"module": "invoice", "action": "update", "description": "Modifier des factures"},
    "payment.view": {"module": "payment", "action": "view", "description": "Voir les paiements"},
    "payment.create": {"module": "payment", "action": "create", "description": "Creer des paiements"},
    "quote.view": {"module": "quote", "action": "view", "description": "Voir les devis"},
    "quote.create": {"module": "quote", "action": "create", "description": "Creer des devis"},
    "supplier.view": {"module": "supplier", "action": "view", "description": "Voir les fournisseurs"},
    "supplier.create": {"module": "supplier", "action": "create", "description": "Creer des fournisseurs"},
    "supplier.update": {"module": "supplier", "action": "update", "description": "Modifier des fournisseurs"},
    "purchase_order.view": {"module": "purchase_order", "action": "view", "description": "Voir les commandes d'achat"},
    "purchase_order.create": {"module": "purchase_order", "action": "create", "description": "Creer des commandes d'achat"},
    "profile.view": {"module": "profile", "action": "view", "description": "Voir son profil"},
    "profile.update": {"module": "profile", "action": "update", "description": "Modifier son profil"},
    "compte.view": {"module": "compte", "action": "view", "description": "Voir les comptes"},
    "compte.create": {"module": "compte", "action": "create", "description": "Creer des comptes"},
    "compte.update": {"module": "compte", "action": "update", "description": "Modifier des comptes"},
    "compte.delete": {"module": "compte", "action": "delete", "description": "Supprimer des comptes"},
    "ecriture.view": {"module": "ecriture", "action": "view", "description": "Voir les ecritures"},
    "ecriture.create": {"module": "ecriture", "action": "create", "description": "Creer des ecritures"},
    "ecriture.update": {"module": "ecriture", "action": "update", "description": "Modifier des ecritures"},
    "ecriture.delete": {"module": "ecriture", "action": "delete", "description": "Supprimer des ecritures"},
    "tresorerie.view": {"module": "tresorerie", "action": "view", "description": "Voir la tresorerie"},
    "tresorerie.create": {"module": "tresorerie", "action": "create", "description": "Creer des mouvements de tresorerie"},
    "tresorerie.update": {"module": "tresorerie", "action": "update", "description": "Modifier des mouvements de tresorerie"},
    "tresorerie.delete": {"module": "tresorerie", "action": "delete", "description": "Supprimer des mouvements de tresorerie"},
    "employe.view": {"module": "rh", "action": "view", "description": "Voir les employes"},
    "employe.create": {"module": "rh", "action": "create", "description": "Creer des employes"},
    "employe.update": {"module": "rh", "action": "update", "description": "Modifier des employes"},
    "employe.delete": {"module": "rh", "action": "delete", "description": "Supprimer des employes"},
    "presence.view": {"module": "rh", "action": "view", "description": "Voir les presences"},
    "presence.create": {"module": "rh", "action": "create", "description": "Creer des presences"},
    "presence.update": {"module": "rh", "action": "update", "description": "Modifier des presences"},
    "presence.delete": {"module": "rh", "action": "delete", "description": "Supprimer des presences"},
    "salaire.view": {"module": "rh", "action": "view", "description": "Voir les salaires"},
    "salaire.create": {"module": "rh", "action": "create", "description": "Creer des salaires"},
    "salaire.update": {"module": "rh", "action": "update", "description": "Modifier des salaires"},
    "salaire.delete": {"module": "rh", "action": "delete", "description": "Supprimer des salaires"},
    "prime.view": {"module": "rh", "action": "view", "description": "Voir les primes"},
    "prime.create": {"module": "rh", "action": "create", "description": "Creer des primes"},
    "prime.update": {"module": "rh", "action": "update", "description": "Modifier des primes"},
    "prime.delete": {"module": "rh", "action": "delete", "description": "Supprimer des primes"},
    "stagiaire.view": {"module": "rh", "action": "view", "description": "Voir les stagiaires"},
    "stagiaire.create": {"module": "rh", "action": "create", "description": "Creer des stagiaires"},
    "stagiaire.update": {"module": "rh", "action": "update", "description": "Modifier des stagiaires"},
    "stagiaire.delete": {"module": "rh", "action": "delete", "description": "Supprimer des stagiaires"},
    "delivery.view": {"module": "delivery", "action": "view", "description": "Voir les livraisons"},
    "delivery.update": {"module": "delivery", "action": "update", "description": "Modifier les livraisons"},
    "dashboard.view": {"module": "dashboard", "action": "view", "description": "Voir le tableau de bord"},
    "notification.view": {"module": "profile", "action": "view", "description": "Voir les notifications"},
    "notification.update": {"module": "profile", "action": "update", "description": "Marquer les notifications comme lues"},
    "notification.manage": {"module": "admin", "action": "manage", "description": "Creer/supprimer des notifications (admin)"},
    "admin.access": {"module": "admin", "action": "access", "description": "Acces a la gestion admin (roles, permissions)"},
    "manager.access": {"module": "admin", "action": "access", "description": "Acces manager"},
    "super_admin.access": {"module": "admin", "action": "access", "description": "Acces super admin (plateforme)"},
}

ROLE_PERMISSIONS = {
    "super_admin": ["*"],
    "admin": [
        "admin.access",
        "client.create", "client.update", "client.delete", "client.view",
        "compte.create", "compte.update", "compte.view",
        "ecriture.create", "ecriture.update", "ecriture.view",
        "invoice.create", "invoice.update", "invoice.view",
        "notification.manage", "notification.update", "notification.view",
        "payment.create", "payment.view",
        "product.create", "product.update", "product.delete", "product.view",
        "profile.update", "profile.view",
        "purchase_order.create", "purchase_order.view",
        "quote.create", "quote.view",
        "report.view",
        "sale.create", "sale.update", "sale.view", "sale.delete",
        "stock.update", "stock.view",
        "supplier.create", "supplier.update", "supplier.view",
        "tresorerie.create", "tresorerie.update", "tresorerie.view",
        "user.create", "user.update", "user.view",
        # RH : un admin de tenant gère aussi les ressources humaines.
        "employe.view", "employe.create", "employe.update", "employe.delete",
        "presence.view", "presence.create", "presence.update", "presence.delete",
        "salaire.view", "salaire.create", "salaire.update", "salaire.delete",
        "prime.view", "prime.create", "prime.update", "prime.delete",
        "stagiaire.view", "stagiaire.create", "stagiaire.update", "stagiaire.delete",
        # Livraisons : l'admin voit et gère les livraisons.
        "delivery.view", "delivery.update",
    ],
    "manager": [
        "client.create", "client.update", "client.view",
        "compte.update", "compte.view",
        "ecriture.create", "ecriture.update", "ecriture.view",
        "invoice.create", "invoice.update", "invoice.view",
        "notification.update", "notification.view",
        "payment.create", "payment.view",
        "product.create", "product.update", "product.view",
        "profile.update", "profile.view",
        "purchase_order.create", "purchase_order.view",
        "quote.create", "quote.view",
        "report.view",
        "sale.create", "sale.update", "sale.view",
        "stock.update", "stock.view",
        "supplier.create", "supplier.update", "supplier.view",
        "tresorerie.create", "tresorerie.update", "tresorerie.view",
        "user.create", "user.update", "user.view",
    ],
    "sales": [
        "client.create", "client.update", "client.view",
        "invoice.create", "invoice.update", "invoice.view",
        "notification.update", "notification.view",
        "payment.create", "payment.view",
        "product.view",
        "profile.update", "profile.view",
        "quote.create", "quote.view",
        "report.view",
        "sale.create", "sale.update", "sale.view",
        "stock.view",
        "supplier.view",
    ],
    "stock": [
        "client.view",
        "notification.update", "notification.view",
        "product.create", "product.update", "product.view",
        "profile.update", "profile.view",
        "purchase_order.create", "purchase_order.view",
        "report.view",
        "stock.update", "stock.view",
        "supplier.create", "supplier.update", "supplier.view",
    ],
    "accountant": [
        "compte.create", "compte.update", "compte.view",
        "ecriture.create", "ecriture.update", "ecriture.view",
        "invoice.view", "invoice.update",
        "notification.update", "notification.view",
        "payment.create", "payment.view",
        "profile.update", "profile.view",
        "report.view",
        "sale.view",
        "tresorerie.create", "tresorerie.update", "tresorerie.view",
    ],
    "user": [
        "client.view",
        "notification.update", "notification.view",
        "product.view",
        "invoice.view",
        "payment.view",
        "quote.view",
        "sale.view",
        "stock.view",
        "report.view",
        "profile.view",
        "profile.update",
    ],
    "rh": [
        "employe.view", "employe.create", "employe.update", "employe.delete",
        "notification.update", "notification.view",
        "presence.view", "presence.create", "presence.update", "presence.delete",
        "salaire.view", "salaire.create", "salaire.update", "salaire.delete",
        "prime.view", "prime.create", "prime.update", "prime.delete",
        "stagiaire.view", "stagiaire.create", "stagiaire.update", "stagiaire.delete",
        "profile.view", "profile.update",
        "report.view",
    ],
    "support": [
        "notification.view",
        "product.view",
        "sale.view",
        "client.view",
        "invoice.view",
        "payment.view",
        "profile.view",
    ],
    "livreur": [
        "delivery.view",
        "delivery.update",
        "notification.update", "notification.view",
        "profile.view",
        "profile.update",
    ],
}

PERMISSIONS = ROLE_PERMISSIONS
